### ISSUE TITLE
Error for installing conda environment

### ISSUE THREAD

**Issue by TheDarkKnight-21th** [shubhamprshr27/NeglectedTailsVLM#4]
<img width="505" alt="image" src="https://github.com/shubhamprshr27/NeglectedTailsVLM/assets/85755635/76d3e728-c25b-4d19-b48b-d2848e5813da">
<img width="548" alt="image" src="https://github.com/shubhamprshr27/NeglectedTailsVLM/assets/85755635/3a545515-ecf3-410d-90c8-b9aadf007835">

there is some error like above. what should i do? my gpu is H100 and OS is linux.

thank you.

**Comment by shubhamprshr27** [comment]
Hi @TheDarkKnight-21th ,
We haven't faced this issue, as my collaborators have also used this repo for installation. But in general, the libraries used were
1. PyTorch 2 and CUDNN 12
2. Numpy
3. Scipy
4. TorchMetrics

**Comment by tian1327** [comment]
Hi there, you can refer to the environment installation in our recent work [SWAT](https://github.com/tian1327/SWAT/blob/master/env.md). It should work for REAL.

**Comment by shubhamprshr27** [comment]
I will close this issue for now.
