### ISSUE TITLE
Deriving synonyms

### ISSUE THREAD

**Issue by xiaojieyin** [shubhamprshr27/NeglectedTailsVLM#5]
Hi, 
I am having trouble deriving synonyms as per the prompt “What are some common ways of referring to {concept}?” in the paper, the generated synonyms with GPT-4 are different from the .json in analysis/laion (Filtering has been considered), can you provide a more detailed prompt or code for this?

**Comment by shubhamprshr27** [comment]
Hi,
Thanks for reaching out, is it okay if you can remind us after NeurIPS rebuttal ? We can help you with the code, which we have forgotten to add to the main repo. Also to correct you, we had queried GPT-3.5-Turbo and this was before August last year ( roughly an year at this point ), so that may also be causing some differences.

**Comment by xiaojieyin** [comment]
Thanks for the reply and good luck with rebuttal!!

**Comment by tian1327** [comment]
@xiaojieyin Hi there, thanks for your interest! I have added the code for query synonyms using GPT-3.5/4 in our new work [SWAT](https://github.com/tian1327/SWAT/tree/master/retrieval). You can check out the detailed instructions in step 1 of [RETRIEVAL.md](https://github.com/tian1327/SWAT/blob/master/retrieval/RETRIEVAL.md).

From my experience, GPT-4 gives more diverse synonyms than GPT-3.5, e.g. some synonyms in other languages than English, as well as some short acronyms. The output from GPT-4 could be more noisy than GPT-3.5. Hence, I suggest you conduct manual filtering to remove some noisy names. 

We used GPT-3.5-turbo for getting our synonyms. Note that as the OpenAI models and pipelines are constantly updated, you may get different outputs from ours.

**Comment by xiaojieyin** [comment]
Thank you for your code, it has been very helpful to us!!

Best regards, Xiaojie.
